### ISSUE TITLE
libjson0-dev dependency install-issues

### ISSUE THREAD

**Issue by sleepdefic1t** [emersonmello/doorlock_raspberrypi#1]
Raspberry Pi Zero W
Jessie Stretch lite

```sudo apt-get install libjson0-dev```
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libjson0-dev
```

So I ```sudo nano /etc/apt/sources.list```, 
then add the line ```deb http://ftp.de.debian.org/debian jessie main```;
per instructions @ [**libjson0-dev packages.debian.org**](https://packages.debian.org/jessie/armhf/libjson0-dev/download).

Next,
```sudo apt-get update```.

Then,
```sudo apt-get install libjson0-dev``` returns ```libjson0-dev : Depends: libjson-c-dev (= 0.11-4)```.

so I, 
```sudo apt-get install libjson-c-dev=0.11-4```.

Finally, ```sudo apt-get install libjson0-dev``` installs okay.

**Comment by sleepdefic1t** [comment]
Checking it out futher...

https://github.com/TurboGit/hubicfuse/issues/139

libjson0-dev is deprecated in Raspbian Stretch.

```sudo apt-get install libjson-c-dev``` will install the correct frameworks. ```libjson-c-dev``` &  ```libjson-c3```

**Comment by emersonmello** [comment]
Hi @sleepdefic1t ,

Thank you so much. I made changes on Readme.md.

**Comment by sleepdefic1t** [comment]
Not a problem. 

I'm working on something similar and yours is by far one of the most well done I've seen!
Keep up the great work!

**Comment by GowrishankarGeek** [comment]
Hi @sleepdefic1t,
The same library I am trying to install in alpine docker image. can you please help on that.
